### PR TITLE
Add configuration to allow invalid SSL certificates

### PR DESCRIPTION
**Pull request by Tomczik76**
This PR adds a new optional config to allow invalid SSL certificates.

### CODE REVIEW

**Comment by Tomczik76** [comment]
@rozza I created this PR because we are evaluating this connector and in our lower level environments we don't have legitimate SSL certificates. Let me know what you think of the change or if you have any questions.

**Comment by rozza** [comment]
Hi @Tomczik76 

Thanks for the PR - I've added [KAFKA-236](https://jira.mongodb.org/projects/KAFKA/issues/KAFKA-236) to track this. We'll look to schedule in our next planning meeting.

Ross

**Comment by Tomczik76** [comment]
Hi @rozza 
I see that KAFKA-236 has been closed but this PR hasn't been merged. Can you give me an update? 
Thanks,
Ryan

**Comment by rozza** [comment]
Hi @Tomczik76,

KAFKA-236 has been triaged and moved to open and is scheduled for the next (1.7.0) release of the connector. Unfortunately, it just missed out due to time on 1.6.0 inclusion.

I think some minor config name change (to mirror the SSLSettings.invalidHostNameAllowed) and a log warning if set will be added for the release. But I'm happy to apply that change to your code.

Just to note there is no set ETA on the 1.7.0 release yet.

Ross

**Comment by rozza** [comment]
@Tomczik76 Apologies for the delay, during triage for the 1.7.0 release it was noted this is already supported via the connections string: see the [tlsAllowInvalidHostnames](https://docs.mongodb.com/manual/reference/connection-string/#mongodb-urioption-urioption.tlsAllowInvalidHostnames) option.

As such adding a configuration is not needed.

Apologies, for not noting this initially when the PR was submitted.

**Pull request closed without merging**
