### PR TITLE
Ensure deterministic schema record names

### PR DESCRIPTION
**Pull request by rayokota**
This is just an example of how to ensure deterministic schema record names, it needs to be tested thoroughly

### CODE REVIEW

**Comment by rozza** [comment]
Hi @rayokota,

Thanks for the PR. Currently the schema names are deterministic as they use the hashcode of the Schema for the name.

I think the issue is two schemas that could be compatible aren't because they generate different names? That errodes the compatibility. Is that the case?

If an optional field that contained a document from document 1 was missing from document 2. Then the inferred schema from document 2 even using a counter would generate names that aren't compatible.

Ross

**Comment by rayokota** [comment]
Hi @rozza , 

A recent PR to Schema Registry (https://github.com/confluentinc/schema-registry/pull/1775) found that the MongoDB connector is generating incompatible names in some cases, with the hashcodes being different in certain scenarios.  

I think if each `"name"` can just be the field name, that would be ideal.  Then the name at the root level could be something like `"default"`.  WDYT?

cc @rajdangwal

**Comment by rajdangwal** [comment]
Hi @rozza and @rayokota,

Based on our discussions, I have raised another [PR](https://github.com/mongodb/mongo-kafka/pull/65) that uses field names for naming the sub-documents.

Thanks.

**Comment by rozza** [comment]
Thanks @rajdangwal  I'll close this PR and review the new one.

**Pull request closed without merging**
