### PR TITLE
Add regular expressions in topic mapping

### PR DESCRIPTION
**Pull request by JeanFrancoisGuena**
Hi,

I wrote this PR to give users the ability to map change stream messages to topics through regular expressions.

Say that you want all messages from databases starting with "myDb-" mapped to a unique topic, you just have to provide a key-value pair in 'topic.namespace.map' JSON object like this: `{"/myDb-.*/": "myUniqueTopic", ...}`

You may be more specific with regular expressions of the form `"/myDb-.*\\.myColl-.*/"` (it looks like a namespace) that take precedence over `"/myDb-.*/"` ones for example. Notice that these mapping come **after** the ones defined without regex, but **before** the "*" wildcard...

Additionally, I introduced `<database>` and `<collection>` reserved words the user may use to add respectively database name and collection name to the topic. For example,  `{"/myDb-.*/": "myDbTopics.<collection>", ...}` would map messages from databases starting with "myDb-" to a topic named `myDbTopics.<the actual collection name picked from change stream document>`.

I did this to try and stay as compliant as possible with `DefaultTopicMapper` behavior...

Every regular expression must begin and end with the slash character, otherwise we wouldn't know they are regular expressions.

Use of regular expressions requires that default topic mapper be a new `EnrichedTopicMapper` class. So, user has to provide the `topic.mapper=com.mongodb.kafka.connect.source.topic.mapping.EnrichedTopicMapper` configuration.

I did it, not to modify `DefaultTopicMapper` code, however I moved `DefaultTopicMapper` code to a new `AbstractTopicMapper` abstract class, that both `DefaultTopicMapper` and `EnrichedTopicMapper` extend. This way, more topic mapper classes could easily be added in the future...?

I updated `MongoSourceConfig` accordingly, but I do not know where to update the official documentation :-(

Of course, I added unit tests, even if I confess more could be added...

Unfortunately, I was not able to create any JIRA feature request before I submit this PR.

Happy reviewing :-)

### CODE REVIEW

**Comment by JeanFrancoisGuena** [comment]
Hi there,

any chance this PR could be reviewed soon ?

Regards

**Comment by JeanFrancoisGuena** [comment]
Hi there,

I was finally able to create a JIRA issue: https://jira.mongodb.org/browse/KAFKA-252

Regards

**Comment by rozza** [comment]
Hi @JeanFrancoisGuena thanks for the PR and the Jira ticket. 

It will be reviewed by the product team in due course - definitely in before the next planned release (1.7.0).

**Comment by JeanFrancoisGuena** [comment]
Hi there, I'm on retirement now... so, I close this PR.

Happy coding everyone :-)

**Comment by Gatsby-Lee** [comment]
> Hi there, I'm on retirement now... so, I close this PR.
> 
> Happy coding everyone :-)

congratulation :)

**Comment by stIncMale** [comment]
We finally got to the functionality requested in this PR: https://github.com/mongodb/mongo-kafka/pull/141.

@JeanFrancoisGuena I am not sure if you care, pinging you just in case.

**Pull request closed without merging**
