### PR TITLE
Add sinking JSON records from Attunity CDC (Qlik Replicate)

### PR DESCRIPTION
**Pull request by abraham-leal**
Hey guys, recently found myself having to write this custom CDC handler, and wanted to PR it in case it was of interest to integrate it to the project.

This introduces a new handler for the Sink. It largely follows the template of previous RDBMS handlers, but configured to work with the structure and naming of Attunity (now Qlik Repliate) CDC from DBs. It includes some unit testing.

Lmk if interested, if not, we can close this PR.

### CODE REVIEW

**Comment by rozza** [comment]
Thanks @abraham-leal we're definitely interested and will review in due course.

**Comment by rozza** [comment]
Marked for 1.5.0 see: [KAFKA-194](https://jira.mongodb.org/projects/KAFKA/issues/KAFKA-194)

**Comment by abraham-leal** [comment]
@rozza Glad this made it into 1.5.0, as we saw more behavior in production we applied a couple of fixes to account for some Qlik Replicate behavior. I'll implement these this week to make sure its ready for review/merge.

**Comment by rozza** [comment]
Hi @abraham-leal - I notice that the [operation values](https://github.com/mongodb/mongo-kafka/pull/18/files#diff-d69b71f2c2a8c45160cef5b6f0c91697eb98172a00e3c0f1fc73a88e050e5aa7R109-R123) this handles are:

-  "INSERT"
-  "REFRESH"
-  "READ"
-  "UPDATE"
-  "DELETE"

Yet in the tests there is a "CREATE" type mentioned? Is that an error or should that type also be handled?

Also I noticed from the [Qlik Kafka documentation](https://help.qlik.com/en-US/replicate/November2020-SR1/Content/Replicate/Main/Kafka/Data%20and%20Metadata%20Messages.htm) there are Full Load and CDC operation types. Do you know anything about those types?

Ross

**Comment by abraham-leal** [comment]
Hi @rozza,

Not a mistake, as you can see there, when `INSERT` or `REFRESH` are received, we return a `c` for `CREATE`. 
To the handler, there are no `INSERT` or `REFRESH`, just `CREATE` a seen [here](https://github.com/mongodb/mongo-kafka/pull/18/files#diff-a2618c828560258472abaf3b0c51c6d655cca4dd3b7193627a7280503b5bcd35R43-R48).
The only reason to do this is to maintain the standard of common CRUD handling with other CDC handlers.

Yep, full loads are the `REFRESH` types, which are treated as inserts since multiple full loads would want to overwrite each other.

**Comment by rozza** [comment]
Hi @abraham-leal I've added #61 which contains this code squashed into the first commit and then some stylistic refactorings in the second commit.

It would be great if you could review.

**Pull request closed without merging**
