### PR TITLE
K210

### PR DESCRIPTION
**Pull request by rozza**
This includes #65 and ensures that the naming convention uses the field name of the parent object.

So the following object with produce the following names:

```
{a: {b: {c: [123]}}}
```

* "default": `{a: {b: {c: [123]}}}`
* "a": `{b: {c: [123]}}`
* "a_b": `{c: [123]}`
* "a_b_c": `[123]`

### CODE REVIEW

**Review by rayokota — APPROVED** [review]
Thanks @rozza , this looks like it will fix the backward compatibility issues found by the recent Schema Registry change (confluentinc/schema-registry#1775).  LGTM

**Comment by rajdangwal** [comment]
Thanks @rozza. The changes looks good to me.

**Comment by rozza** [comment]
Many thanks @rajdangwal - I've fixed the conflict in the cli and this is now in master.

**Comment by rajdangwal** [comment]
Thanks a lot @rozza for taking this up.
Thank you so much @rayokota for all the help and initiatives.

**Pull request closed without merging**
